// <auto-generated />
using System;
using Contacts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20231114210544_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contacts.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ContactId");

                    b.HasIndex("MobilePhone")
                        .IsUnique()
                        .HasFilter("[MobilePhone] IS NOT NULL");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = new Guid("d1dbd8dc-0446-4236-aafa-c02e33a02819"),
                            BirthDate = new DateTime(2003, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Student",
                            MobilePhone = "+375 29 873 17 77",
                            Name = "Dasha"
                        },
                        new
                        {
                            ContactId = new Guid("6a7c694c-3193-4185-bae5-dfe5128fc046"),
                            BirthDate = new DateTime(2002, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Programmer",
                            MobilePhone = "+375296658376",
                            Name = "Ilya"
                        },
                        new
                        {
                            ContactId = new Guid("df17d593-11bc-4b33-bfb5-381f817591e6"),
                            BirthDate = new DateTime(2003, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Teacher",
                            MobilePhone = "+375(29) 463-76-13",
                            Name = "Dima"
                        },
                        new
                        {
                            ContactId = new Guid("d06e3790-0b96-444d-9b2c-1664320a77e6"),
                            BirthDate = new DateTime(2003, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Dancer",
                            MobilePhone = "+375(29)3178954",
                            Name = "Ksusha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
